### ISSUE TITLE
using Data.Time.getZonedTime causes exception, undefined symbol

### ISSUE THREAD

**Issue by cliffordbeshers** [ghcjs/ghcjs-base#16]
The following program:

import Data.Time
main = getZonedTime >>= print 

Generates this error in console:

uncaught exception in Haskell main thread: ReferenceError: h$get_current_timezone_seconds is not defined
ReferenceError: h$get_current_timezone_seconds is not defined
    at h$$q1 (out.js:18651)
    at h$mainLoop (rts.js:9519)
    at rts.js:3632
    at runIfPresent (rts.js:3650)
    at onGlobalMessage (rts.js:3691)

$ ghcjs --version
The Glorious Glasgow Haskell Compilation System for JavaScript, version 0.1.0 (GHC 7.8.3.20141119)

**Comment by luite** [comment]
this is actually a missing function from the `time` package, but it should be added

**Comment by luite** [comment]
JS doesn't know the actual time zone name unfortunately. I have the following implementation that works here:

```{.javascript}
function h$get_current_timezone_seconds(t, pdst_v, pdst_o, pname_v, pname_o) {
    var d      = new Date(t);
    var now    = new Date();
    var jan    = new Date(now.getFullYear(),0,1);
    var jul    = new Date(now.getFullYear(),0,1);
    var stdOff = Math.max(jan.getTimezoneOffset(), jul.getTimezoneOffset());
    var isDst  = d.getTimezoneOffset() < stdOff;
    var tzo    = d.getTimezoneOffset();
    pdst_v.dv.setInt32(pdst_o, isDst ? 1 : 0, true);
    if(!pname_v.arr) pname_v.arr = [];
    var offstr = tzo < 0 ? ('+' + (tzo/-60)) : ('' + (tzo/-60));
    pname_v.arr[pname_o] = [h$encodeUtf8("UTC" + offstr), 0];
    return (3600-60*tzo)|0;
}

```

The last line looks a bit off though, adding an hour. Anyone interested in checking if this works for all dst situations and all time zones?

**Comment by hamishmack** [comment]
It works here in NZST in winter time:

```
$ node test2.jsexe/all.js
2017-07-07 19:12:29.223 UTC+12
```

That's like 0.05% of the worlds population covered for half the year.
