### ISSUE TITLE
Bring back ToJSString / FromJSString? (improved-base)

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs-base#30]
The definition in ghcjs-dom seems reasonable https://github.com/ghcjs/ghcjs-dom/blob/master/src/GHCJS/DOM/Types.hs#L984, though maybe instead of using empty typeclasses, they could instead be defined like this:

```haskell
class ToJSString a where
    toJSString :: a -> JSString
    default toJSString :: (PToJSRef a, ToJSRef a) => a -> JSString
    toJSString = pFromJSRef . pToJSRef
```

Or maybe it's good that it forces you to make your `toJSRef` also be a conversion to string?

**Comment by hamishmack** [comment]
> Or maybe it's good that it forces you to make your toJSRef also be a conversion to string?

I think it might be confusing if `toJSRef` and `toJSString` could produce a different JS value.

Something else to ponder, should there be `ToJSNumber` to `ToJSBool` constraints too?  If so are these all just special cases of a more general `ToJS` constraint.

Also do we need `ToJS` and `FromJS` or would `JSType` be better?

Could we make constraints like this work:
``` Haskell
boolFunction :: (JSType a ~ Bool, ToJSRef a) => a -> IO ()
numberFunction :: (JSType a ~ Double, ToJSRef a) => a -> IO ()
stringFunction :: (JSType a ~ JSString, ToJSRef a) => a -> IO ()
```

Then could we define ToJSString like this?
``` Haskell
type ToJSString a = (JSType a ~ JSString, ToJSRef a)
```

**Comment by mgsloan** [comment]
Right, it seems like a more generic mechanism would be best.  I like the idea of a `JSType a` type family.  I'd like to not have tons of typeclasses, though, so maybe it's best to modify `FromJSRef` / `ToJSRef`.

I'm scheming on some pretty major changes to the marshaling classes - https://github.com/ghcjs/ghcjs-base/issues/24 and https://github.com/ghcjs/ghcjs/issues/391.  Maybe it'd be good to also rename them to `ToJS` and `FromJS` at that point.

Here's what I'm thinking:

```haskell
type family JSType a

class FromJS a where
    fromJS :: JSType a -> IO a
    -- ... other methods ...

class ToJS a where
    toJS :: a -> IO (JSType a)
    -- ... other methods ...
```

E.g. a definition for `Text` might look like

```haskell
type instance JSType Text = JSString
instance ToJS Text where toJS = textToJSString
instance FromJS Text where fromJS = textFromJSString
```

One thing this complicates is the `fromJSRefListOf` trick used to efficiently convert `[Char]` to `JSString`.  We'd also need a `JSListType` type family in order to do that, and it'd be annoying to need to define it for all instances of `FromJS` / `ToJS`.  I've pondered this a bit, and the only good solution I've come up with is using a closed type family to special case String.  This of course has the downside that then we can't provide optimized conversions from `[]`, but I think it's worth it:

```haskell
type family JSListType a where
    JSListType Char = JSString
    JSListType a = JSArray a     -- NOTE: this is wrong.  Why'd the type parameter get dropped from JSArray?

class (Coercible (JSListType a) JSRef) => ListToJS a where
    listToJS :: [a] -> JSListType a

instance ToJS a => ListToJS a where
    listToJS = coerce . Prim.toJSArray <=< mapM toJS

instance ListToJS Char where
    listToJS = Prim.toJSString

type instance JSType [a] = JSListType a

instance ListToJS a => ToJS [a] where
    toJS = listToJS
```
(haven't tried this, but I think it ought to work)

**Comment by luite** [comment]
```{.haskell}
boolFunction :: (JSType a ~ Bool, ToJSRef a) => a -> IO ()
numberFunction :: (JSType a ~ Double, ToJSRef a) => a -> IO ()
stringFunction :: (JSType a ~ JSString, ToJSRef a) => a -> IO ()
```
`Double` and `Bool` still need some marshalling, even though the FFI desugaring code does this automatically. I'm not sure if we should accept these, perhaps this instead?

```{.haskell}
newtype Boolean = Boolean JSRef deriving Typeable
instance IsJSRef Boolean
data Number = Number JSRef deriving Typeable
instance IsJSRef Number

boolFunction :: (JSType a ~ Boolean, ToJSRef a) => a -> IO ()
numberFunction :: (JSType a ~ Number, ToJSRef a) => a -> IO ()
stringFunction :: (JSType a ~ JSString, ToJSRef a) => a -> IO ()
```

Then we can actually have an `IsJSRef` superclass constraint on the `JSType a`

**Comment by mgsloan** [comment]
@luite Yup, I think that's a good approach.  It meshes well with my typescript stuff as well.

I'm thinking that fundeps are better for this.  This means that toJS / fromJS aren't restricted to agree on their types, but that would be unconventional.

```
class IsJSRef r => ToJS a r | a -> r where
  toJS :: a -> IO r
class IsJSRef r => FromJS a r | a -> r where
  fromJS :: r -> IO a
```

The type parameter order is designed to work nicely with infix - (String `ToJS` JSString), hah (-XTypeOperators)!

```haskell
instance Text `ToJS` JSString where toJS = textToJSString
instance Text `FromJS` JSString where fromJS = textFromJSString
```

**Comment by mgsloan** [comment]
I think functional dependencies are the way to go.  Here's my reasoning:

* The `JSType` type family only really has meaning for these marshaling classes - I can't think of any other use for it.

* It's conceivable that someone would want to have `ToJS ComplexADT ComplexObject` and `FromJS SimpleADT ComplexObject`.  For example, if you never care about marshaling a bunch of functions from JS, but you do need to provide them when marshaling to it.  While this could conceivably be confusing, I think allowing this is better, because then you can still take advantage of the generic defaults for things with polymorphic fields:

```
data Foo a = Foo { foo :: a }
  deriving (Generic)
instance ToJS a => ToJS (Foo a) JSRef
instance FromJS a => FromJS (Foo a) JSRef
```

Then, we also have `ToJS (Foo ComplexADT) JSRef` and `FromJS (Foo SimpleADT) JSRef`.

**Comment by mgsloan** [comment]
Nevermind, type families win.  The issue is that when defining new ref types, with the fundep version you can't use GeneralizedNewtypeDeriving, and instead have to write some verbose and inefficient ugliness like:

```haskell
newtype Foo = Foo JSRef
instance ToJS Foo Foo where toJS = return
instance FromJS Foo Foo where fromJS = return
```

By flipping around the class's type parameters, it's possible to eliminate the boilerplate and get back the efficiency of GND.  However, this means you lose type info and have things like `toJS :: [JSString] -> [JSRef]`.  Yuck!

```haskell
newtype Foo = Foo JSRef deriving (ToJS JSRef, FromJS JSRef)
```

Things work out nicely with the type family solution:

```haskell
newtype Foo = Foo JSRef
  deriving (IsJSRef, ToJS, FromJS)
type instance JSType Foo = Foo
```

The `ComplexADT` / `SimpleADT` case described above is purely hypothetical anyway.  Not a very convincing reason.

**Comment by mgsloan** [comment]
I'm closing this issue, as it pretty much turned into a variety of design iterations, and will be confusing to the bystander.  Thanks for the discussion, y'all!

The marshaling saga carries on here https://github.com/ghcjs/ghcjs/issues/419
