### ISSUE TITLE
Migration guide 

### ISSUE THREAD

**Issue by mgsloan** [ghcjs/ghcjs-base#31]
It would be good to have a migration guide to improved-base.  Here's rough a start, just notes as I was working on converting ghcjs-jquery (which is still [WIP](https://github.com/mgsloan/ghcjs-jquery/tree/improved-base)): https://gist.github.com/mgsloan/b33f071f99f73810acff

**Comment by hamishmack** [comment]
I think most ghcjs users have probably migrated now or started using ghcjs after improved-base was merged.
