### ISSUE TITLE
Add return value for synchronous callbacks

### ISSUE THREAD

**Issue by luite** [ghcjs/ghcjs-base#37]
calling into Haskell from JS is a common task, and often a return value is needed in some way. Synchronous callbacks don't return a value currently, but they could. This would require converting the signalling mechanism for blocking to an exception.

This should probably be added to the `ghcjs-base` library, with some documentation on the limitations of synchronous tasks.

**Comment by luite** [comment]
done

**Comment by chadaustin** [comment]
Thank you so much -- we're using it already.  :)  We're building a language (vaguely ML-ish, compiles to JavaScript) written in Haskell and compiling the compiler to JavaScript with GHCJS for the browser playground ( http://cruxlang.org/try/ ) and for easy installation via npm ( https://www.npmjs.com/package/cruxlang ).   Just wanted to say thanks for your amazing work on ghcjs!
