### ISSUE TITLE
Dereferencing an exported (0 :: Int) fails

### ISSUE THREAD

**Issue by wereHamster** [ghcjs/ghcjs-base#44]
`Int` prim type is represented as JavaScript integer, so this check in `h$derefExport` wrongfully fails:

```javascript
if (!e.root) return null;
```

Same problem with anything that is represented in JavaScript as a falsy value (`false`, `undefined`, empty string).

**Comment by luite** [comment]
good point. keep in mind that you can only export lifted values though, these are always either a number, a boolean or a heap object. but this is indeed wrong, and a bit tricky to reproduce even.

**Comment by wereHamster** [comment]
I didn't have any trouble reproduce it ;)

```haskell
main = withExport (0 :: Int) $ \r -> do
        v <- derefExport r
        print (v :: Maybe Int)
```

prints "Nothing".

**Comment by luite** [comment]
It's easy to export the unevaluated version instead, and if GHC floats it to the top level it also becomes boxed again, and therefore truthy.

I've fixed it now and added it to the test case.
