### ISSUE TITLE
 ReferenceError: h$closeWebSocket is not defined

### ISSUE THREAD

**Issue by agocorona** [ghcjs/ghcjs-base#47]
Here is the program and the error:

https://gist.github.com/agocorona/c1765b72ec915a53489f

**Comment by luite** [comment]
I think this works ok with the latest commit of ghcjs-base

**Comment by agocorona** [comment]
I have unregistered ghcjs-base cloned the last commit, compiled and it still produce the same error....

I'm using windows by the way.

**Comment by agocorona** [comment]
Trying other things.  It may be triggered by another error in my server app....

**Comment by agocorona** [comment]
It appears in chrome, but not in edge/explorer.  I also have some problems with the protocol in the server side. So I will close this until I have a more clear case

**Comment by manyoo** [comment]
I'm reporting here the same problem. I investigated the generated files. In the ghcjs-base installation directory, the generated libHSghcjs-base-0.2.0.0-*-js_a file has the code in jsbits/websocket.js. But the generated lib.js for my app doesn't have the h$openWebSocket, h$closeWebSocket functions from websocket.js! But all code in other jsbits files like jsbits/array.js, jsbits/jsstring.js are all included in the lib.js. Why only the websocket.js code is excluded in the result?  It's really weird.

**Comment by manyoo** [comment]
I tried reinstalling ghcjs-base with the newest version several times and it doesn't help. At last, deleting .ghcjs directory and run 'ghcjs-boot' again solved the problem by installing the latest version in the global directory.  It seems when compiling packages, ghcjs is using the ghcjs-base package in the global directory but not the newer user .ghcjs directory. Is this a problem?

**Comment by hamishmack** [comment]
Looks like this is fixed.
