### ISSUE TITLE
[Question] Kinds of Retentions

### ISSUE THREAD

**Issue by geraldus** [ghcjs/ghcjs-base#6]
I have a question about retention. Consider following code:

``` haskell
foreign import javascript safe "$r = (function () {\
        \var conn = new WebSocket($1);\
        \conn.onmessage = $2;\
        \conn.onopen = $3;\
        \conn.onclose = $4;\
        \return conn;})()"
    js_newWebSocket :: JSString
                    -> JSFun (JSRef a -> IO ())
                    -> JSFun (IO ())
                    -> JSFun (IO ())
                    -> IO WebSocket
configuredWebSocketConnection :: String -> (MessageEvent -> IO ()) -> IO () -> IO () -> IO WebSocket
configuredWebSocketConnection url onms onop oncl = do
    onmscb <- syncCallback1 NeverRetain False (readMsg onms) -- :: (JSRef a -> IO b)
    onopcb <- syncCallback NeverRetain False onop
    onclcb <- syncCallback NeverRetain False oncl
    js_newWebSocket (toJSString url) onmscb onopcb onclcb
    where
        readMsg :: (MessageEvent -> IO()) -> JSRef a -> IO ()
        readMsg f eref = do
            let vref = castRef eref :: JSRef Value
            mv <- fromJSRef vref
            print mv
            case mv >>= parseMaybe parseJSON of
                Just evt -> f evt
                _        -> reportError "Unexpected message from web socket recieved."
```

I have faced retention issue. First when I just tested the concept itself, I've used `AlwaysRetain` to create on—message callback (`onmscb`), at that moment there was no any parsing logic, it just printed `"Message!"` and it worked. Finally, I've introduced conversion from `JSRef` to `MessageEvent`, leaving retention as is. Due to this entire page became completely inaccessible, crashing in short amount of time. This «dead—lock» was resolved by changing retention kind to `NeverRetain`.
So why in first case printing worked, but parsing does not?
And small question, related to retention: what is `CAF`s (they are mentioned in retain description)?

**Comment by luite** [comment]
Retentions are gone now, `releaseCallback` must be called on all created callbacks, which is typically when you know that they won't be called again, or when you know that you have another way to guarantee its reachability (through extensible retention for example).

**Comment by wdanilo** [comment]
@luite where is the `JSFun` now?

**Comment by mgsloan** [comment]
@wdanilo I believe it's now called `Callback` https://github.com/ghcjs/ghcjs-base/blob/master/GHCJS/Foreign/Callback.hs

**Comment by Wizek** [comment]
Thanks @mgsloan, it seems it has indeed been renamed. Was a bit confused when reading earlier code snippets referencing JSFun and not finding it.
