### ISSUE TITLE
Data.JSString.toTitle crashes

### ISSUE THREAD

**Issue by cdsmith** [ghcjs/ghcjs-base#62]
Message is: `ReferenceError: h$u_towtitle is not defined`

**Comment by cdsmith** [comment]
Seems to be caused by Data.Char.toTitle crashing.  So it's most likely a bug in some lower level, really, but I don't know where.

**Comment by hamishmack** [comment]
Missing shim that needs to be added here https://github.com/ghcjs/shims/blob/0a6234261b4b13103ad8be898b93705bcf5dc3ae/src/string.js#L53
