### ISSUE TITLE
Duplicated h$textFromString

### ISSUE THREAD

**Issue by vwwv** [ghcjs/ghcjs-base#74]
- There are 2 implementations of `h$textFromString`
  - [one here](https://github.com/ghcjs/ghcjs-base/blob/552da6d30fd25857a2ee8eb995d01fd4ae606d22/jsbits/text.js)
  - [the other one her](https://github.com/ghcjs/ghcjs-base/blob/552da6d30fd25857a2ee8eb995d01fd4ae606d22/jsbits/string.js)
- It seems only one of them is used, but not sure which.
- Might this issue cause problems when compiling with google's closure compiler? (My text strings containing `\n` trigger exception when optimized with the closure compiler, could this be related? ).
- If there's a reason to have to `h$textFromString`, do you mind adding a comment explaining it?

**Comment by hamishmack** [comment]
Looks like `jsbits/string.js` is not used (only `jsbits/text.js`) is listed in `ghcjs-base.cabal`.  It also looks like `jsbits/string.js` uses an older method to write to the ByteArray.
