### ISSUE TITLE
Submit ghcjs-base to hackage

### ISSUE THREAD

**Issue by crocket** [ghcjs/ghcjs-base#81]
@hamishmack confirmed that ghcjs-boot libraries do not depend on ghcjs-base, so it should be safe to use any version of ghcjs-base from hackage.

I think I can handle this one after https://github.com/ghcjs/ghcjs-base/pull/77 is merged.

I'll try to add anyone, who is enthusiastic and doesn't look malicious or crazy to me, to the maintainer list of ghcjs-base on hackage.

**Comment by tysonzero** [comment]
Any update on this? It would be nice to have this in Hackage.

**Comment by tysonzero** [comment]
@hamishmack @crocket Bump. Is this happening any time soon? I would really like to have ghcjs-base on hackage.

**Comment by luite** [comment]
yes, the boot libraries for ghcjs on ghc 8.2 won't contain `ghcjs-base` anymore

**Comment by nomeata** [comment]
Can we have `ghcjs-base` on hackage? It is a dependency of `jsaddle`, which is on hackage, for example.

**Comment by Ericson2314** [comment]
@luite you mean `ghcjs-base` is gone altogether? We can remove it from `jsaddle`then/

**Comment by nomeata** [comment]
Of course if  `ghcjs-base` is no longer needed for  `jaddle`, then an upload to Hackage may not be that important.

**Comment by nomeata** [comment]
`reflex` and related packages were updated on hackage, but depend on `ghcjs-base`:
http://hackage.haskell.org/package/reflex-0.5/reflex.cabal

While it is possible to use `reflex` with GHC without using `ghcjs-base`, it is still required for building when GHCJS, it seems, to having `ghcjs-base` on hackage too would be nice.

**Comment by nomeata** [comment]
Independent of `reflex`, it seems that `jsaddle-dom` depends on `ghcjs-base`.

**Comment by Ericson2314** [comment]
CC @luigy

**Comment by hamishmack** [comment]
I have uploaded latest master branch to hackage.
