### ISSUE TITLE
Export constructor for JSString

### ISSUE THREAD

**Issue by s9gf4ult** [ghcjs/ghcjs-base#84]
Is there any reason to not export `JSString` constructor? It is implemented as newtype around `JSVal` and not exported constructor cause to use `unsafeCoerce :: JSVal -> JSString` and vise versa instead of `coerce` or explicit packing/unpacking.

**Comment by hamishmack** [comment]
IIRC `pToJSVal` and `pFromJSVal` should work (and `jsval` will also get the `JSVal` for a `JSString`).    However if you want to be sure your code is portable to GHC you might need to use `toJSVal` and `fromJSVal`.

For instance in [jsaddle (which tries to provide a ghcjs-base compatible interface on GHC)](https://hackage.haskell.org/package/jsaddle-0.8.0.1), `JSString` is `newtype JSString = JSString Text`.  This allows for pure conversion to/from `Text` ([Data.JSString.Text](https://hackage.haskell.org/package/jsaddle-0.8.0.1/docs/Data-JSString-Text.html)), but requires conversion to/from `JSVal` must be done with `toJSVal` and `fromJSVal` (the monad is needed to determine the JavaScript context to create the `JSVal` in).
