### ISSUE TITLE
Missing pattern match in GHCJS/Marshal/Internal.hs

### ISSUE THREAD

**Issue by louispan** [ghcjs/ghcjs-base#89]
In `instance (GFromJSArr (a p), GFromJSArr (b p)) => GFromJSArr ((a :*: b) p) where`
https://github.com/ghcjs/ghcjs-base/blob/dd7034ef8582ea8a175a71a988393a9d1ee86d6f/GHCJS/Marshal/Internal.hs#L220

    Pattern match(es) are non-exhaustive
    In a case alternative: Patterns not matched: Nothing

**Comment by hamishmack** [comment]
Duplicate of #64
