### ISSUE TITLE
JavaScript.Web.WebSocket: ReadyState does not map to readyState constants

### ISSUE THREAD

**Issue by eamsden** [ghcjs/ghcjs-base#94]
# Synopsis

The `ReadyState` type exported by `JavaScript.Web.WebSocket` has an enum instance which is used to marshall it from the `readyState` property of a websocket. This enum instance does not properly map the integer constants to `ReadyState` values. The possible values of the `readyState` property are given at https://developer.mozilla.org/en-US/docs/Web/API/WebSocket#Ready_state_constants

# Expected behavior

```
getReadyState myWebSocket
```

returns the ready state of the websocket.

# Actual behavior

```
getReadyState myWebSocket
```

throws the following exception to the console:

```
toEnum{ReadyState}: tag (3) is outside of enumeration's range (0,2)
CallStack (from HasCallStack):
  error, called at ./JavaScript/Web/WebSocket.hs:71:29 in ghcjs-base-0.2.0.0-GiGsdYOoO5CISyJ2m7ax9F:JavaScript.Web.WebSocket
```

# Cause

The `ReadyState` type is written

```
data ReadyState = Closed | Connecting | Connected
  deriving (Data, Typeable, Enum, Eq, Ord, Show)
```

and decoded by

```
getReadyState ws = fmap toEnum (js_getReadyState ws)
```

The Enum instance derived by the `deriving` clause does not map to the ready states given in the WebSocket API documentation.

**Comment by eamsden** [comment]
I've made a pull request #95  which fixes this issue.

**Comment by luigy** [comment]
Good catch! I wonder if functionality that is available from `ghcjs-dom` should be eventually removed from `ghcjs-base`.  [`ghcjs-dom`](https://github.com/ghcjs/ghcjs-dom/blob/d13e77f6f8252db8c5e3e1502f90fe5d3902fa87/ghcjs-dom-jsffi/src/GHCJS/DOM/JSFFI/Generated/WebSocket.hs#L105-L108)  has the advantage that is auto generated from the IDL files and this kind of bugs are unlikely to come up

**Comment by eamsden** [comment]
Is ghcjs-dom now the preferred way to access Javascript API functionality? If so, this should be stated somewhere more clearly than it is right now.
